# Generated by Django 5.2.8 on 2025-11-29 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActividadPantalla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_pantalla",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Inicio de Sesión"),
                            ("REGISTRO", "Registro"),
                            ("LISTA_LECCIONES", "Lista de Lecciones"),
                            ("LISTA_TEMAS", "Lista de Temas"),
                            ("CONTENIDO_TEMA", "Contenido de Tema"),
                            ("EJERCICIOS", "Ejercicios"),
                            ("RESULTADOS", "Resultados"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp_entrada", models.DateTimeField(auto_now_add=True)),
                ("timestamp_salida", models.DateTimeField(blank=True, null=True)),
                (
                    "tiempo_segundos",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tiempo total en segundos en esta pantalla",
                        null=True,
                    ),
                ),
                (
                    "veces_volver_contenido",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de veces que presionó el botón 'Volver' en el contenido del tema",
                    ),
                ),
                (
                    "detalles_extra",
                    models.JSONField(
                        blank=True,
                        help_text="Información adicional específica de la pantalla (JSON)",
                        null=True,
                    ),
                ),
                (
                    "ejercicio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lessons.ejercicio",
                    ),
                ),
                (
                    "leccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lessons.leccion",
                    ),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lessons.tema",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null para pantallas pre-login",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad en Pantalla",
                "verbose_name_plural": "Actividades en Pantallas",
                "ordering": ["-timestamp_entrada"],
            },
        ),
        migrations.CreateModel(
            name="ProgresoTema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("SIN_INICIAR", "Sin Iniciar"),
                            ("INICIADO", "Iniciado"),
                            ("COMPLETADO", "Completado"),
                        ],
                        default="SIN_INICIAR",
                        max_length=20,
                    ),
                ),
                (
                    "desbloqueado",
                    models.BooleanField(
                        default=False,
                        help_text="Si el tema está disponible para el usuario",
                    ),
                ),
                ("ejercicios_intentados", models.PositiveIntegerField(default=0)),
                ("ejercicios_correctos", models.PositiveIntegerField(default=0)),
                ("ejercicios_incorrectos", models.PositiveIntegerField(default=0)),
                (
                    "porcentaje_acierto",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "volvio_de_ejercicios_a_tema",
                    models.BooleanField(
                        default=False,
                        help_text="Si el usuario regresó de ejercicios a ver el tema",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lessons.tema"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progreso_temas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de Tema",
                "verbose_name_plural": "Progreso de Temas",
                "ordering": ["usuario", "tema__leccion__orden", "tema__orden"],
                "unique_together": {("usuario", "tema")},
            },
        ),
        migrations.CreateModel(
            name="RespuestaEjercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respuesta_usuario", models.CharField(max_length=500)),
                ("es_correcta", models.BooleanField()),
                (
                    "uso_ayuda",
                    models.BooleanField(
                        default=False, help_text="Si el usuario solicitó ver la ayuda"
                    ),
                ),
                ("fecha_respuesta", models.DateTimeField(auto_now_add=True)),
                (
                    "tiempo_respuesta_segundos",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tiempo en segundos desde que vio el ejercicio hasta que respondió",
                        null=True,
                    ),
                ),
                (
                    "ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessons.ejercicio",
                    ),
                ),
                (
                    "progreso_tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="tracking.progresotema",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de Ejercicio",
                "verbose_name_plural": "Respuestas de Ejercicios",
                "ordering": ["-fecha_respuesta"],
            },
        ),
        migrations.CreateModel(
            name="SesionEstudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "duracion_total_segundos",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duración total de la sesión", null=True
                    ),
                ),
                ("temas_visitados", models.PositiveIntegerField(default=0)),
                ("ejercicios_intentados", models.PositiveIntegerField(default=0)),
                ("ejercicios_correctos", models.PositiveIntegerField(default=0)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Estudio",
                "verbose_name_plural": "Sesiones de Estudio",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ProgresoLeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iniciada", models.BooleanField(default=False)),
                ("completada", models.BooleanField(default=False)),
                (
                    "porcentaje_completado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Porcentaje de temas completados en esta lección",
                        max_digits=5,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "leccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessons.leccion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progreso_lecciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de Lección",
                "verbose_name_plural": "Progreso de Lecciones",
                "ordering": ["usuario", "leccion__orden"],
                "unique_together": {("usuario", "leccion")},
            },
        ),
    ]
