# Generated by Django 5.2.8 on 2025-11-29 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Leccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "orden",
                    models.PositiveIntegerField(
                        help_text="Orden de aparición en el frontend", unique=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si está inactiva, no se mostrará en el frontend",
                        verbose_name="Activa",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lección",
                "verbose_name_plural": "Lecciones",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Tema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "orden",
                    models.PositiveIntegerField(help_text="Orden dentro de la lección"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si está inactivo, no se mostrará en el frontend",
                        verbose_name="Activo",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "leccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temas",
                        to="lessons.leccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tema",
                "verbose_name_plural": "Temas",
                "ordering": ["leccion__orden", "orden"],
                "unique_together": {("leccion", "orden")},
            },
        ),
        migrations.CreateModel(
            name="Ejercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        help_text="Orden dentro del tema (número de ejercicio)"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ABIERTO", "Respuesta Abierta"),
                            ("MULTIPLE", "Opción Múltiple"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "dificultad",
                    models.CharField(
                        choices=[
                            ("FACIL", "Fácil"),
                            ("INTERMEDIO", "Intermedio"),
                            ("DIFICIL", "Difícil"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "instruccion",
                    models.TextField(help_text="Instrucciones para el estudiante"),
                ),
                (
                    "enunciado",
                    models.TextField(
                        help_text="El ejercicio en sí (puede incluir HTML básico)",
                        verbose_name="Ejercicio",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen opcional para el ejercicio",
                        null=True,
                        upload_to="ejercicios/",
                    ),
                ),
                (
                    "respuesta_correcta",
                    models.CharField(
                        help_text="Para abiertos: respuesta exacta. Para múltiple: letra de opción correcta (A, B, C, D)",
                        max_length=500,
                    ),
                ),
                (
                    "texto_ayuda",
                    models.TextField(
                        blank=True,
                        help_text="Texto que se muestra al presionar 'Ayuda'",
                    ),
                ),
                (
                    "retroalimentacion_correcta",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje cuando la respuesta es correcta",
                        verbose_name="Retroalimentación (correcta)",
                    ),
                ),
                (
                    "retroalimentacion_incorrecta",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje cuando la respuesta es incorrecta",
                        verbose_name="Retroalimentación (incorrecta)",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejercicios",
                        to="lessons.tema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejercicio",
                "verbose_name_plural": "Ejercicios",
                "ordering": ["tema", "orden"],
                "unique_together": {("tema", "orden")},
            },
        ),
        migrations.CreateModel(
            name="OpcionMultiple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letra",
                    models.CharField(
                        choices=[
                            ("A", "Opción A"),
                            ("B", "Opción B"),
                            ("C", "Opción C"),
                            ("D", "Opción D"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "texto",
                    models.CharField(help_text="Texto de la opción", max_length=500),
                ),
                (
                    "ejercicio",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "MULTIPLE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="lessons.ejercicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opción Múltiple",
                "verbose_name_plural": "Opciones Múltiples",
                "ordering": ["ejercicio", "letra"],
                "unique_together": {("ejercicio", "letra")},
            },
        ),
        migrations.CreateModel(
            name="ContenidoTema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TEORIA", "Teoría"),
                            ("EJEMPLO", "Ejemplo"),
                            ("EJEMPLO_EXTRA", "Ejemplo Extra"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        help_text="Orden de aparición dentro del tema"
                    ),
                ),
                (
                    "contenido_texto",
                    models.TextField(
                        help_text="Contenido en HTML (puede incluir formato básico)"
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen opcional para el contenido",
                        null=True,
                        upload_to="contenido_temas/",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contenidos",
                        to="lessons.tema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contenido de Tema",
                "verbose_name_plural": "Contenidos de Temas",
                "ordering": ["tema", "orden"],
                "unique_together": {("tema", "orden")},
            },
        ),
    ]
