# Generated by Django 5.2.8 on 2025-11-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contenidotema",
            name="imagen",
        ),
        migrations.RemoveField(
            model_name="ejercicio",
            name="imagen",
        ),
        migrations.AddField(
            model_name="ejercicio",
            name="mostrar_dificultad",
            field=models.BooleanField(
                default=False,
                help_text="Si se marca, la dificultad será visible para el estudiante",
                verbose_name="Mostrar dificultad",
            ),
        ),
        migrations.AlterField(
            model_name="contenidotema",
            name="contenido_texto",
            field=models.TextField(
                help_text="Contenido en HTML desde TinyMCE (incluye formato, imágenes, tablas, etc.)"
            ),
        ),
        migrations.AlterField(
            model_name="ejercicio",
            name="enunciado",
            field=models.TextField(
                help_text="El ejercicio en sí (soporta HTML desde TinyMCE, incluye imágenes)",
                verbose_name="Ejercicio",
            ),
        ),
        migrations.AlterField(
            model_name="ejercicio",
            name="instruccion",
            field=models.TextField(
                help_text="Instrucciones para el estudiante (soporta HTML desde TinyMCE)"
            ),
        ),
        migrations.AlterField(
            model_name="ejercicio",
            name="retroalimentacion_correcta",
            field=models.TextField(
                blank=True,
                help_text="Mensaje cuando la respuesta es correcta (soporta HTML desde TinyMCE)",
                verbose_name="Retroalimentación (correcta)",
            ),
        ),
        migrations.AlterField(
            model_name="ejercicio",
            name="retroalimentacion_incorrecta",
            field=models.TextField(
                blank=True,
                help_text="Mensaje cuando la respuesta es incorrecta (soporta HTML desde TinyMCE)",
                verbose_name="Retroalimentación (incorrecta)",
            ),
        ),
        migrations.AlterField(
            model_name="ejercicio",
            name="texto_ayuda",
            field=models.TextField(
                blank=True,
                help_text="Texto que se muestra al presionar 'Ayuda' (soporta HTML desde TinyMCE)",
            ),
        ),
        migrations.AlterField(
            model_name="leccion",
            name="descripcion",
            field=models.TextField(
                help_text="Descripción de la lección (soporta HTML desde TinyMCE)"
            ),
        ),
        migrations.AlterField(
            model_name="tema",
            name="descripcion",
            field=models.TextField(
                help_text="Descripción del tema (soporta HTML desde TinyMCE)"
            ),
        ),
    ]
